#include <stdio.h>
#include <string.h>

int main() {
    char elements[2000][3] = {
        "H", "He", "Li", "Be", "B", "C", "N", "O", "F", "Ne",
        "Na", "Mg", "Al", "Si", "P", "S", "Cl", "Ar", "K", "Ca"
    };
    
    char input1[3], input2[3];
    char equations[200000][300] = {
        "H2 + He -> no reaction",
        "H2 + Li -> 2LiH",
        "H2 + Be -> BeH2",
        "H2 + B -> no reaction",
        "H2 + C -> no reaction",
        "H2 + N2 -> no reaction",
        "2H2 + O2 -> 2H2O",
        "H2 + F2 -> 2HF",
        "H2 + Ne -> no reaction",
        "H2 + Na -> 2NaH",
        "H2 + Mg -> MgH2",
        "H2 + Al -> AlH3",
        "H2 + Si -> no reaction",
        "H2 + P -> no reaction",
        "H2 + S -> H2S",
        "H2 + Cl2 -> 2HCl",
        "H2 + Ar -> no reaction",
        "H2 + K -> 2KH",
        "H2 + Ca -> CaH2",
        "H2 + Sc -> ScH2",
        "H2 + O2 -> 2H2O"
        
        
        "He + H -> no reaction",
		"He + He -> no reaction",
		"He + Li -> no reaction",
		"He + Be -> no reaction",
		"He + B -> no reaction",
		"He + C -> no reaction",
		"He + N -> no reaction",
		"He + O -> no reaction",
		"He + F -> no reaction",
		"He + Ne -> no reaction",
		"He + Na -> no reaction",
		"He + Mg -> no reaction",
		"He + Al -> no reaction",
		"He + Si -> no reaction",
		"He + P -> no reaction",
		"He + S -> no reaction",
		"He + Cl -> no reaction",
		"He + Ar -> no reaction",
		"He + K -> no reaction",
		"He + Ca -> no reaction",
		
		"Li + H -> LiH",
		"Li + He -> no reaction",
		"Li + Li -> Li2",
		"Li + Be -> LiBe",
		"Li + B -> no reaction",
		"Li + C -> no reaction",
		"Li + N -> no reaction",
		"Li + O -> no reaction",
		"Li + F -> LiF",
		"Li + Ne -> no reaction",
		"Li + Na -> LiNa",
		"Li + Mg -> LiMg",
		"Li + Al -> LiAlH4",
		"Li + Si -> LiSi",
		"Li + P -> Li3P",
		"Li + S -> Li2S",
		"Li + Cl -> LiCl",
		"Li + Ar -> no reaction",
		"Li + K -> LiK",
		"Li + Ca -> LiCa",
		
		
		"Be + H -> BeH2",
		"Be + He -> no reaction",
		"Be + Li -> LiBe",
		"Be + Be -> Be2",
		"Be + B -> no reaction",
		"Be + C -> no reaction",
		"Be + N -> no reaction",
		"Be + O -> no reaction",
		"Be + F -> no reaction",
		"Be + Ne -> no reaction",
		"Be + Na -> no reaction",
		"Be + Mg -> no reaction",
		"Be + Al -> no reaction",
		"Be + Si -> no reaction",
		"Be + P -> no reaction",
		"Be + S -> no reaction",
		"Be + Cl -> no reaction",
		"Be + Ar -> no reaction",
		"Be + K -> no reaction",
		"Be + Ca -> CaBe2",
		
		"B + H -> BH3",
		"B + He -> no reaction",
		"B + Li -> no reaction",
		"B + Be -> no reaction",
		"B + B -> B2",
		"B + C -> BC",
		"B + N -> BN",
		"B + O -> BO",
		"B + F -> BF3",
		"B + Ne -> no reaction",
		"B + Na -> no reaction",
		"B + Mg -> no reaction",
		"B + Al -> AlB2",
		"B + Si -> SiB3",
		"B + P -> BP",
		"B + S -> BS",
		"B + Cl -> BCl3",
		"B + Ar -> no reaction",
		"B + K -> no reaction",
		"B + Ca -> no reaction",
		
		
		"C + H -> CH",
		"C + He -> no reaction",
		"C + Li -> no reaction",
		"C + Be -> no reaction",
		"C + B -> no reaction",
		"C + C -> C2",
		"C + N -> CN",
		"C + O -> CO",
		"C + F -> CF",
		"C + Ne -> no reaction",
		"C + Na -> no reaction",
		"C + Mg -> no reaction",
		"C + Al -> no reaction",
		"C + Si -> SiC",
		"C + P -> no reaction",
		"C + S -> CS2",
		"C + Cl -> CCl4",
		"C + Ar -> no reaction",
		"C + K -> no reaction",
		"C + Ca -> CaC2",
		
		"N2 + H2 -> NH3",
		"N2 + He -> no reaction",
		"N2 + Li -> no reaction",
		"N2 + Be -> no reaction",
		"N2 + B -> no reaction",
		"N2 + C -> no reaction",
		"N2 + N -> no reaction",
		"N2 + O2 -> 2NO",
		"N2 + F2 -> no reaction",
		"N2 + Ne -> no reaction",
		"N2 + Na -> Na3N",
		"N2 + Mg -> Mg3N2",
		"N2 + Al -> AlN",
		"N2 + Si -> Si3N4",
		"N2 + P -> no reaction",
		"N2 + S -> no reaction",
		"N2 + Cl2 -> 2NCl",
		"N2 + Ar -> no reaction",
		"N2 + K -> K3N",
		"N2 + Ca -> Ca3N2",
		
		
		"O2 + H2 -> H2O",
		"O2 + He -> no reaction",
		"O2 + Li -> no reaction",
		"O2 + Be -> no reaction",
		"O2 + B -> no reaction",
		"O2 + C -> CO2",
		"O2 + N2 -> 2NO",
		"O2 + F2 -> no reaction",
		"O2 + Ne -> no reaction",
		"O2 + Na -> Na2O2",
		"O2 + Mg -> MgO",
		"O2 + Al -> Al2O3",
		"O2 + Si -> SiO2",
		"O2 + P4 -> P4O10",
		"O2 + S -> SO2",
		"O2 + Cl2 -> 2ClO",
		"O2 + Ar -> no reaction",
		"O2 + K -> KO2",
		"O2 + Ca -> CaO",
		
		
		"F2 + H2 -> 2HF",
		"F2 + He -> no reaction",
		"F2 + Li -> LiF",
		"F2 + Be -> no reaction",
		"F2 + B -> no reaction",
		"F2 + C -> no reaction",
		"F2 + N2 -> no reaction",
		"F2 + O2 -> no reaction",
		"F2 + Ne -> no reaction",
		"F2 + Na -> NaF",
		"F2 + Mg -> MgF2",
		"F2 + Al -> AlF3",
		"F2 + Si -> SiF4",
		"F2 + P -> PF5",
		"F2 + S -> SF6",
		"F2 + Cl2 -> 2ClF",
		"F2 + Ar -> no reaction",
		"F2 + K -> KF",
		"F2 + Ca -> CaF2",
		
		
		"Ne + H2 -> no reaction",
		"Ne + He -> no reaction",
		"Ne + Li -> no reaction",
		"Ne + Be -> no reaction",
		"Ne + B -> no reaction",
		"Ne + C -> no reaction",
		"Ne + N2 -> no reaction",
		"Ne + O2 -> no reaction",
		"Ne + F2 -> no reaction",
		"Ne + Ne -> no reaction",
		"Ne + Na -> no reaction",
		"Ne + Mg -> no reaction",
		"Ne + Al -> no reaction",
		"Ne + Si -> no reaction",
		"Ne + P -> no reaction",
		"Ne + S -> no reaction",
		"Ne + Cl2 -> no reaction",
		"Ne + Ar -> no reaction",
		"Ne + K -> no reaction",
		"Ne + Ca -> no reaction",
		
		"Na + H -> NaH",
		"Na + He -> no reaction",
		"Na + Li -> LiNa",
		"Na + Be -> no reaction",
		"Na + B -> no reaction",
		"Na + C -> no reaction",
		"Na + N -> Na3N",
		"Na + O -> Na2O",
		"Na + F -> NaF",
		"Na + Ne -> no reaction",
		"Na + Mg -> NaMg",
		"Na + Al -> Na3Al",
		"Na + Si -> Na4Si",
		"Na + P -> Na3P",
		"Na + S -> Na2S",
		"Na + Cl -> NaCl",
		"Na + Ar -> no reaction",
		"Na + K -> KNa",
		"Na + Ca -> CaNa",
		
		
		"Mg + H -> MgH2",
		"Mg + He -> no reaction",
		"Mg + Li -> no reaction",
		"Mg + Be -> no reaction",
		"Mg + B -> no reaction",
		"Mg + C -> no reaction",
		"Mg + N -> no reaction",
		"Mg + O -> MgO",
		"Mg + F -> MgF2",
		"Mg + Ne -> no reaction",
		"Mg + Na -> NaMg",
		"Mg + Al -> Mg2Al3",
		"Mg + Si -> Mg2Si",
		"Mg + P -> Mg3P2",
		"Mg + S -> MgS",
		"Mg + Cl -> MgCl2",
		"Mg + Ar -> no reaction",
		"Mg + K -> KMg",
		"Mg + Ca -> CaMg",
		
		
		"Al + H -> AlH3",
		"Al + He -> no reaction",
		"Al + Li -> LiAlH4",
		"Al + Be -> no reaction",
		"Al + B -> AlB2",
		"Al + C -> Al4C3",
		"Al + N -> AlN",
		"Al + O -> Al2O3",
		"Al + F -> AlF3",
		"Al + Ne -> no reaction",
		"Al + Na -> Na3Al",
		"Al + Mg -> Mg2Al3",
		"Al + Si -> AlSi3",
		"Al + P -> AlP",
		"Al + S -> Al2S3",
		"Al + Cl -> AlCl3",
		"Al + Ar -> no reaction",
		"Al + K -> K3Al",
		"Al + Ca -> CaAl2",
		
		
		"Si + H -> SiH4",
		"Si + He -> no reaction",
		"Si + Li -> no reaction",
		"Si + Be -> no reaction",
		"Si + B -> no reaction",
		"Si + C -> no reaction",
		"Si + N -> no reaction",
		"Si + O -> SiO2",
		"Si + F -> SiF4",
		"Si + Ne -> no reaction",
		"Si + Na -> no reaction",
		"Si + Mg -> Mg2Si",
		"Si + Al -> AlSi3",
		"Si + P -> no reaction",
		"Si + S -> SiS2",
		"Si + Cl -> SiCl4",
		"Si + Ar -> no reaction",
		"Si + K -> K4Si",
		"Si + Ca -> CaSi",
		
		"P + H -> PH3",
		"P + He -> no reaction",
		"P + Li -> Li3P",
		"P + Be -> no reaction",
		"P + B -> BP",
		"P + C -> no reaction",
		"P + N -> PN",
		"P + O -> P4O6 or P4O10",
		"P + F2 -> PF3 or PF5",
		"P + Ne -> no reaction",
		"P + Na -> Na3P",
		"P + Mg -> Mg3P2",
		"P + Al -> AlP",
		"P + Si -> SiP2",
		"P + S -> P4S3 or P4S10",
		"P + Cl2 -> PCl3 or PCl5",
		"P + Ar -> no reaction",
		"P + K -> K3P",
		"P + Ca -> Ca3P2",
		
		"S + H -> H2S",
		"S + He -> no reaction",
		"S + Li -> no reaction",
		"S + Be -> no reaction",
		"S + B -> no reaction",
		"S + C -> no reaction",
		"S + N -> NS2 or N2S3",
		"S + O -> SO2 or SO3",
		"S + F -> SF2 or SF4 or SF6",
		"S + Ne -> no reaction,"
		"S + Na -> Na2S or Na2S2 or Na2S3",
		"S + Mg -> MgS",
		"S + Al -> Al2S3",
		"S + Si -> SiS2",
		"S + P -> P4S3 or P4S10",
		"S + Cl2 -> SCl2 or SCl4 or S2Cl2 or S2Cl6",
		"S + Ar -> no reaction",
		"S + K -> KS2",
		"S + Ca -> CaS",
		
		"Cl + H -> HCl",
		"Cl + He -> no reaction",
		"Cl + Li -> no reaction",
		"Cl + Be -> no reaction",
		"Cl + B -> no reaction",
		"Cl + C -> no reaction",
		"Cl + N -> no reaction",
		"Cl + O -> no reaction",
		"Cl + F -> ClF or ClF3 or ClF5",
		"Cl + Ne -> no reaction",
		"Cl + Na -> NaCl",
		"Cl + Mg -> MgCl2",
		"Cl + Al -> AlCl3",
		"Cl + Si -> SiCl4",
		"Cl + P -> PCl3 or PCl5",
		"Cl + S -> SCl2 or SCl4 or S2Cl2 or S2Cl6",
		"Cl + Ar -> no reaction",
		"Cl + K -> KCl",
		"Cl + Ca -> CaCl2",
		
		"Ar + H -> no reaction",
		"Ar + He -> no reaction",
		"Ar + Li -> no reaction",
		"Ar + Be -> no reaction",
		"Ar + B -> no reaction",
		"Ar + C -> no reaction",
		"Ar + N -> no reaction",
		"Ar + O -> no reaction",
		"Ar + F -> no reaction",
		"Ar + Ne -> no reaction",
		"Ar + Na -> no reaction",
		"Ar + Mg -> no reaction",
		"Ar + Al -> no reaction",
		"Ar + Si -> no reaction",
		"Ar + P -> no reaction",
		"Ar + S -> no reaction",
		"Ar + Cl -> no reaction",
		"Ar + K -> no reaction",
		"Ar + Ca -> no reaction",
		
		"K + H -> KH",
		"K + He -> no reaction",
		"K + Li -> no reaction",
		"K + Be -> no reaction",
		"K + B -> no reaction",
		"K + C -> no reaction",
		"K + N -> no reaction",
		"K + O -> no reaction",
		"K + F -> KF",
		"K + Ne -> no reaction",
		"K + Na -> KNa",
		"K + Mg -> KMg",
		"K + Al -> KAlH4",
		"K + Si -> KSi",
		"K + P -> KP",
		"K + S -> K2S",
		"K + Cl -> KCl",
		"K + Ar -> no reaction",
		"K + Ca -> KCaH2",
		
		"Ca + H -> CaH2",
		"Ca + He -> no reaction",
		"Ca + Li -> no reaction",
		"Ca + Be -> no reaction",
		"Ca + B -> no reaction",
		"Ca + C -> no reaction",
		"Ca + N -> no reaction",
		"Ca + O -> no reaction",
		"Ca + F -> no reaction",
		"Ca + Ne -> no reaction",
		"Ca + Na -> no reaction",
		"Ca + Mg -> no reaction",
		"Ca + Al -> no reaction",
		"Ca + Si -> no reaction",
		"Ca + P -> Ca3P2",
		"Ca + S -> CaS",
		"Ca + Cl -> CaCl2",
		"Ca + Ar -> no reaction",
		"Ca + K -> KCa",
		"Ca + Sc -> no reaction"

		
    };
    
       int continue_program = 1; // initialize flag variable to 1
    
    while (continue_program) { // loop until flag is 0
        printf("Enter two elements from the periodic table:\n");
        printf("Element 1: ");
        scanf("%s", input1);
        printf("Element 2: ");
        scanf("%s", input2);
    
        printf("You entered: %s, %s\n", input1, input2);
        
        int i, j, eq_found = 0;
        for (i = 0; i < 20; i++) {
            if (strcmp(input1, elements[i]) == 0 || strcmp(input2, elements[i]) == 0) {
                for (j = 0; j < 20; j++) {
                    if (strstr(equations[j], input1) != NULL && strstr(equations[j], input2) != NULL) {
                        printf("%s\n", equations[j]);
                        eq_found = 1;
                        break;
                    }
                }
                if (eq_found) {
                    break;
                }
            }
        }
        if (!eq_found) {
            printf("No equation found for %s and %s\n", input1, input2);
        }
        
        // Ask user if they want to continue
        printf("Do you want to continue? (Enter ON to continue or OFF to exit): ");
        char continue_input[4];
        scanf("%s", continue_input);
        if (strcmp(continue_input, "OFF") == 0) {
            continue_program = 0; // set flag to 0 to exit loop
        }
    }
    
    return 0;
}
